### ISSUE TITLE
Will the shell code of running your project be available soon?

### ISSUE THREAD

**Issue by ywh-my** [a43992899/DeID-VC#1]
thank you

**Comment by ywh-my** [comment]
and I have anther problem :

**Comment by ywh-my** [comment]
and I have anther problem : 
 After the training of Stage one and two , When training the PSG VAE model , how can we get the input of the E_vae of S_embedding? Are these S_embedding extracted from the E_s in  trained and finetuned AutoVC?

**Comment by a43992899** [comment]
Yes, it will be available soon! I haven't cleaned up my code yet. I will work on this after icassp deadline.

And yes, the training targets of the E_vae are extracted from the E_s.
