### ISSUE TITLE
Code incompatibility while converting generated mel-spectrograms to waveforms

### ISSUE THREAD

**Issue by huangf79** [a43992899/DeID-VC#2]
Hello, the [hifi-gan](https://github.com/a43992899/DeID-VC/tree/main/deid/hifi-gan) codes you provided seems to be incompatible with [deid/autovc/conversion.ipynb](https://github.com/a43992899/DeID-VC/blob/main/deid/autovc/conversion.ipynb) or [deid/autovc/vocoder_hifigan.ipynb](https://github.com/a43992899/DeID-VC/blob/main/deid/autovc/vocoder_hifigan.ipynb), both of which need to call [hifi-gan/inference_e2e.py](https://github.com/a43992899/DeID-VC/blob/main/deid/hifi-gan/inference_e2e.py). Have you ever made some modifications in the hifi-gan codes? If yes, could you please provide the modified codes? Thanks!

**Comment by a43992899** [comment]
Thanks for pointing that out, let me check~

**Comment by a43992899** [comment]
I have updated `deid/hifi-gan/inference_e2e.py`, please check.

**Comment by huangf79** [comment]
The codes are working properly, thank you for your time!
